#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTMotor,  HTServo)
#pragma config(Sensor, S2,     lightLeft,      sensorLightActive)
#pragma config(Sensor, S3,     lightRight,     sensorLightActive)
#pragma config(Sensor, S4,     gyroSensor,           sensorI2CHiTechnicGyro)
#pragma config(Motor,  mtr_S1_C1_1,     backLeft,      tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     backRight,     tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_1,     frontLeft,     tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     frontRight,    tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_1,     liftMotor,     tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_2,     intakeMotor,   tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S1_C4_1,    gateServo,            tServoStandard)
#pragma config(Servo,  srvo_S1_C4_2,    servo2,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#define COMPETITION

#include "JoystickDriver.c"
#include "drive.h"
#include "drive.c"
#include "lift.h" //Import other files called in this one
#include "lift.c"
#include "intake.h"
#include "intake.c"
#include "gate.h"
#include "gate.c"
#include "gyro.h"
GyroSys gyr;
#include "gyro.c"

DriveSys drive;
LiftSys lift;
IntakeSys intake; //Control variable declaration
GateSys gate;


void initializeRobot(){ //Robot initiliazation code
	drive.BackLeft = backLeft;
	drive.BackRight = backRight;  //Declare motor control variables
	drive.FrontRight = frontRight;
	drive.FrontLeft = frontLeft;
	gate.gate = gateServo;
	lift.lift = liftMotor;
	intake.intake = intakeMotor;
	gyr.gyroscope = gyroSensor;

	return;
}

/*task main() {
void followLine(){

		if(SensorValue(lightLeft && lightRight) < 80){
			motor[FrontRight]=100;
			motor[FrontLeft]=100; //BOTH light sensor values are <80
			motor[BackRight]=100; //go straight
			motor[BackLeft]=100;
	}


	else if(SensorValue(lightLeft) < 80){
		motor[FrontRight]=100;
		motor[FrontLeft]=0;
		motor[BackRight]=100; //ONLY left light sensor value is <80
		motor[BackLeft]=0; //Turn right
	}


	 	else if(SensorValue(lightRight) < 80){
		motor[FrontRight]=0;
		motor[FrontLeft]=100; //ONLY right light sensor value is <80
		motor[BackRight]=0; //Turn left
		motor[BackLeft]=100;

	 }
}

*/



task main() {

	initializeRobot(); //Calls robot init function

#ifdef COMPETITION
	waitForStart(); //Wait for match start
#endif

//	updateDriveSys (drive, 100, 100); //Sets motor power to full
//	wait1Msec(10000); //Wait 10k milliseconds (10 seconds)
//	updateDriveSys (drive, 0, 0); //Sets motor power to none

//	followLine();

startTask(updateGyroSys);

}
