#pragma config(Sensor, S1,     ultrasonicSensor, sensorSONAR)
#pragma config(Sensor, S2,     colorSensor,    sensorColorNxtFULL)
#pragma config(Sensor, S3,     touchSensor,    sensorTouch)
#pragma config(Motor,  motorB,          rightMotor,    tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  motorC,          leftMotor,     tmotorNXT, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	motor[leftMotor] = 50; //Go straight slowly
	motor[rightMotor] = 50;

	wait1Msec(2000); //Wait 2 seconds

	motor[leftMotor] = -50; //go backwards slowly
	motor[rightMotor] = -50;

	wait1Msec(2000); //Wait 2 seconds

	motor[leftMotor] = 0; //Stop
	motor[rightMotor] = 0;
}









/* __      __________   ________       _____    __________________ .___.___     _____ _____________________._.
/  \    /  \_____  \  \_____  \     /  _  \  /   _____/\_   ___ \|   |   |   /  _  \\______   \__    ___/| |
\   \/\/   //   |   \  /   |   \   /  /_\  \ \_____  \ /    \  \/|   |   |  /  /_\  \|       _/ |    |   | |
 \        //    |    \/    |    \ /    |    \/        \\     \___|   |   | /    |    \    |   \ |    |    \|
  \__/\  / \_______  /\_______  / \____|__  /_______  / \______  /___|___| \____|__  /____|_  / |____|    __
       \/          \/         \/          \/        \/         \/                  \/       \/            \/*/
