#pragma config(Sensor, S1,     ultrasonicSensor, sensorSONAR)
#pragma config(Sensor, S2,     colorSensor,    sensorColorNxtFULL)
#pragma config(Sensor, S3,     touchSensor,    sensorTouch)
#pragma config(Motor,  motorB,          rightMotor,    tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  motorC,          leftMotor,     tmotorNXT, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	motor[leftMotor] = 50;
	motor[rightMotor] = 50;

	wait1Msec(2000);

	motor[leftMotor] = -50;
	motor[rightMotor] = -50;

	wait1Msec(2000);

	motor[leftMotor] = 0;
	motor[rightMotor] = 0;
}
